export const COMPRESS_RESPONSE = 'COMPRESS_RESPONSE';

export enum TokenPair {
  ETHUSDT = 'ETHUSDT',
  BNBUSDT = 'BNBUSDT',
  BTCUSDT = 'BTCUSDT',
  SOLUSDT = 'SOLUSDT',
  RUNEUSDT = 'RUNEUSDT',
  NEARUSDT = 'NEARUSDT',
  MATICUSDT = 'MATICUSDT',
  AVAXUSDT = 'AVAXUSDT',
  ARBUSDT = 'ARBUSDT',
}

export enum MicroserviceEvent {
  CANDLE_LATEST_ALL = `CANDLE.LATEST.ALL`,
  INDICATOR_LATEST_ALL = `INDICATOR.LATEST.ALL`,
  CANDLE_INDEX = `CANDLE.INDEX`,
  INDICATOR_INDEX = `INDICATOR.INDEX`,
  INDICATOR_FREQ_INDEX = `INDICATOR.FREQ.INDEX`,
  INDICATOR_INDEX_V2 = `INDICATOR.INDEX.V3`,
}
