services:
  mongo:
    image: mongo:7.0
    ports:
      - 27024:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret@123
      - MONGO_INITDB_DATABASE=arexa-trader-view
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongo-data:
