app:
  env: APP_ENV
  name: APP_NAME
logger:
  level: LOGGER_LEVEL
  useFile:
    __name: LOGGER_USE_FILE
    __format: json
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  username: REDIS_USER_NAME
  password: REDIS_PASSWORD
mongodb:
  uri: MONGODB_URI
nats:
  host: NATS_HOST
  port: NATS_PORT
interval:
  refresh: INTERVAL_REFRESH
  sleepTime: INTERVAL_SLEEP_TIME
response:
  limit: RESPONSE_LIMIT
