app:
  env: development
  name: "seriezer-trader-view"
logger:
  level: info
  useFile: false
redis:
  host: localhost
  port: 6379
  username: default
  password: redis_pw
mongodb:
  uri: mongodb://127.0.0.1:27017/nest-base
  debug: false
nats:
  host: 206.189.146.23
  port: 42222
tokenPairs:
  - ETHUSDT
  - BNBUSDT
  - BTCUSDT
  - SOLUSDT
  - RUNEUSDT
  - NEARUSDT
  - MATICUSDT
  - TIA/USDT
  - AVAXUSDT
  - ARBUSDT
interval:
  refresh: 60000
  sleepTime: 10000
response:
  limit: 300
