app:
  env: development
  name: "nest-be-template"
  port: 3001
  host: localhost
  url: http://localhost:3001
  brandName: "nest-be-template"
  brandUrl: https://nest-be-template.example
throttle:
  ttl: 60
  limit: 10
queue:
  job:
    attempts: 10
    removeOnComplete: true
    removeOnFail: false
auth:
  jwt:
    secretKey: secret
    expireTime: 7d
  refreshToken:
    secretKey: secret
    expireTime: 7d
  verifyToken:
    secretKet: secret
    expireTime: 1d
logger:
  level: info
  useFile: false
redis:
  host: localhost
  port: 6379
  username: default
  password: redis_pw
mongodb:
  uri: mongodb://127.0.0.1:27017/nest-base
